### PR TITLE
Add bash script for seeding the database

### PR DESCRIPTION
**Pull request by mgjeffries**
# Description
Developers are lazy and efficient, and want to be able to quickly toss out all the junk text that they toss into the database while they are testing out features. This change adds a bash script that developers can use to remove their local copy of the database, and rebuild it from the fixtures, by running `sh seed.sh`
## Type of change
- [ ] New feature (non-breaking change which adds functionality)
# How Has This Been Tested?
Please describe step-by-step the process that a reviewer can follow to adequately test this PR. 
- [ ] Warning: This step will delete everything from db.sql Make sure that you have a backup of important data. It will also destroy your current migrations. Run `sh seed.sh` from the command line
- [ ] Verify that the new migrations have been created, and that the data is updated in the client.
# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by skratz17** [comment]
It seems that I'm having an issue with this seed script... looking at the branch it seems that the change over to the SET_DEFAULT handler as opposed to the SET handler in the Posts model is not in this branch... maybe merging `main` would fix it?

**Comment by mgjeffries** [comment]
Thanks! Should be fixed now. I merged main.

**Review by Michaelr-Tyler — APPROVED** [review]
approved

**Review by skratz17 — APPROVED** [review]
helllll yea this will save much time

**Comment by mgjeffries** [comment]
@skratz17, I added the migrations folder to the gitignore, and removed it from git. Would you mind double checking this?

**Pull request merged**
